name: ui_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  google_maps_flutter: ^1.0.6
  carousel_slider: ^2.3.1
  clipboard: ^0.1.2+8
  url_launcher: ^5.7.10
  share: ^0.6.5+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/